### ISSUE TITLE
Exception while running Step 3 java -jar cpt4.jar 5

### ISSUE THREAD

**Issue by pancodia** [OHDSI/ETL-CMS#30]
After downloading the vocabulary files, I am running the command `java -jar cpt4.jar 5` to append the CPT vocabulary. But I keep getting the following exception:

```
javax.xml.ws.WebServiceException: Failed to access the WSDL at: https://uts-ws.nlm.nih.gov/services/nwsSecurity?wsdl. It failed with:
    java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty.
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(RuntimeWSDLParser.java:251)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:228)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:191)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:160)
    at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:307)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:269)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:205)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:195)
    at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:112)
    at javax.xml.ws.Service.<init>(Service.java:77)
...
```

Also, tried to register and get licensed on UMLS (by following [this](https://github.com/OHDSI/Athena/tree/master/athena-pom/utils/cpt4_jar)). But even I provided the username and password, I still have the same issue. 

Any idea of what's going on? How to solve the issue?

**Comment by ChristopheLambert** [comment]
I had a similar problem a few months ago, and it was a matter of their systems being temporarily down. If the problem persists, the vocabulary project folks maintain that application.

**Comment by ChristopheLambert** [comment]
I'm going to close this out, barring any further communication on the matter.

**Comment by cgreich** [comment]
Wait. Let's get to hte bottom of this. I'll ping the necessary people.

**Comment by pancodia** [comment]
I am still seeing the same exception after a month.
